In [1]:
import numpy as np

In [4]:
a = [1,2,3,5]
a=np.array(a)
print(type(a))
a
print(a.ndim)

<class 'numpy.ndarray'>
1


In [6]:
# 2 dimension
n6 = np.array([[4,5,6],[7,2,7]])
print(n6)
print(n6.ndim)
print(n6.shape)

[[4 5 6]
 [7 2 7]]
2
(2, 3)


In [7]:
# 3 dimensions: array of array of array
n7 = np.array([
    [
        [6,7,2,3],
        [9,10,11,12],
        [0,4,6,5]
    ],
    [
        [10,4,15,120],
        [0,4,6,5],
        [0,4,6,5]
    ]
])
print(n7)
print(n7.ndim)
print(n7.shape)
n7.shape=(6,4)
print(n7)

[[[  6   7   2   3]
  [  9  10  11  12]
  [  0   4   6   5]]

 [[ 10   4  15 120]
  [  0   4   6   5]
  [  0   4   6   5]]]
3
(2, 3, 4)
[[  6   7   2   3]
 [  9  10  11  12]
 [  0   4   6   5]
 [ 10   4  15 120]
 [  0   4   6   5]
 [  0   4   6   5]]
